POST http://localhost:8080/auth/register/
Accept: application/json
Content-Type: application/json

{
  "email":"test@mail2.ru",
  "password":"1234"
}

###

POST http://localhost:8080/auth/login/
Accept: application/json
Content-Type: application/json

{
  "email":"test@mail2.ru",
  "password":"1234"
}

###

PUT http://localhost:8080/auth/login/
Accept: application/json
Content-Type: application/json

{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAbWFpbDIucnUiLCJwYXNzd29yZCI6IjEyMzQiLCJleHAiOjE2NzA0MzYyOTl9.-o7fT2mqB1g9BwF82RPKdk4RDc0WkORdlwjd6MQGxeY",
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3RAbWFpbDIucnUiLCJwYXNzd29yZCI6IjEyMzQiLCJleHAiOjE2NzA0NDMxOTl9.CcUAXRcG1xJuckJmO6X7BLTYACGDv8JXYxJPQ2K3qfg"
}