POST http://localhost:8080/auth/register/
Accept: application/json
Content-Type: application/json

{
  "email":"test@mail2.ru",
    "password":"1234"
}

###

POST http://localhost:8080/auth/login/
Accept: application/json
Content-Type: application/json

{
  "email":"test@mail2.ru",
    "password":"1234"
}